# Generated by Django 4.0.2 on 2022-03-30 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
