# Generated by Django 4.0.2 on 2022-02-16 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_petphoto_pet_user_profile_alter_pet_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='petphoto',
            name='pet_photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.pet'),
            preserve_default=False,
        ),
    ]
