# Generated by Django 4.0.2 on 2022-02-16 06:32

from django.db import migrations, models
import petstagram.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_petphoto_pet_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petphoto',
            name='pet_photo',
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='', validators=[
                petstagram.common.validators.validate_file_max_size_in_mb]),
        ),
        migrations.RemoveField(
            model_name='petphoto',
            name='tagged_pets',
        ),
        migrations.AddField(
            model_name='petphoto',
            name='tagged_pets',
            field=models.ManyToManyField(to='main.Pet'),
        ),
    ]
